/**
 * Dashboard Route Handler
 * GET /api/dashboard - Serves pre-computed dashboard view from S3
 *
 * This route reads pre-computed views generated by the Lambda Aggregator.
 * No database queries - just S3 reads for fast response times.
 */

import { Hono } from 'hono';
import {
  getJsonFromS3,
  getDashboardViewKey,
  getMetaKey,
} from '../lib/s3.js';
import type { DashboardView } from '../lib/types.js';

interface ProcessingMeta {
  lastProcessedAt: string;
  lastProcessingDurationMs: number;
  membersProcessed: number;
  viewsGenerated: string[];
}

const dashboardRoute = new Hono();

/**
 * GET /api/dashboard - Get team overview stats
 * Reads from pre-computed views/dashboard.json
 */
dashboardRoute.get('/', async (c) => {
  try {
    const dashboardView = await getJsonFromS3<DashboardView>(getDashboardViewKey());

    if (!dashboardView) {
      // No pre-computed view yet - return empty state
      return c.json({
        success: true,
        message: 'No data available yet. Aggregator has not run.',
        data: {
          generatedAt: new Date().toISOString(),
          summary: {
            totalCost: 0,
            totalInputTokens: 0,
            totalOutputTokens: 0,
            totalMembers: 0,
            activeMembers: 0,
            avgCostPerMember: 0,
          },
          costChangePercent: 0,
          dailyTrend: [],
          topMembers: [],
          modelDistribution: [],
          recentSyncs: [],
        },
      });
    }

    return c.json({
      success: true,
      data: dashboardView,
    });
  } catch (error) {
    console.error('Dashboard fetch error:', error);
    return c.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        code: 'INTERNAL_ERROR',
      },
      500
    );
  }
});

/**
 * GET /api/dashboard/model-distribution - Get model usage breakdown
 * Data is already included in the main dashboard view
 */
dashboardRoute.get('/model-distribution', async (c) => {
  try {
    const dashboardView = await getJsonFromS3<DashboardView>(getDashboardViewKey());

    if (!dashboardView) {
      return c.json({
        success: true,
        data: [],
      });
    }

    return c.json({
      success: true,
      data: dashboardView.modelDistribution,
    });
  } catch (error) {
    console.error('Model distribution fetch error:', error);
    return c.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        code: 'INTERNAL_ERROR',
      },
      500
    );
  }
});

/**
 * GET /api/dashboard/meta - Get aggregator processing metadata
 */
dashboardRoute.get('/meta', async (c) => {
  try {
    const meta = await getJsonFromS3<ProcessingMeta>(getMetaKey());

    if (!meta) {
      return c.json({
        success: true,
        message: 'No processing metadata available yet',
        data: null,
      });
    }

    return c.json({
      success: true,
      data: meta,
    });
  } catch (error) {
    console.error('Meta fetch error:', error);
    return c.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        code: 'INTERNAL_ERROR',
      },
      500
    );
  }
});

export default dashboardRoute;
